### ISSUE TITLE
Josephine Values 2.0 

### ISSUE THREAD

**Issue by chawang90** [josephine/handbook#11]
While I love our current [Values](https://github.com/josephine/handbook/blob/master/Josephine%20Values.md), I think that we've now been working with them long enough that we can articulate them more meaningfully and succinctly. I was feeling a revamp before, but B's post about ["Values with Teeth"](https://medium.com/two-factor-authenticity/values-with-teeth-68c9fdc31f85#.c0tiklvrh) helped confirm my feelings.

Goals here are to (1) shorten/combine values & (2) make sure that the title/mantra is actually what we use to make decisions and is something we can reference/have referenced in office.

A couple of thoughts: 
1. Cultivate Self-Reliance hasn't ever been said in the office. Instead I think the more colloquial and memorable "Teach 'em How to Fish" would be better. 
2. Serve the Many, Serve the Small feels more like our Labor Mission than a Value. I propose we axe the value and merge with Mission. 
3. Be More Human is a catcher mantra but I think it's a little vague. To me, the core value that this is trying to get at might sound better as "People over things". However, it might make more sense to keep the mantra as Be More Human and have the explanation start off with "this means we put people over things, etc". 
4. Details Are Everything still feels to me like our weakest value. I'd love to combine this with the Measure Feelings Not Things comment about success being measured in pride, not credit. 
5. Measure Feelings Not Things should more explicitly relate to the point that measuring impact is hard, and that measuring things is often an easier substitute for measure impact on human lives, and that we strive for the latter as much as possible.

**Comment by zeke** [comment]
<img width="1227" alt="screen shot 2016-01-20 at 2 40 04 pm" src="https://cloud.githubusercontent.com/assets/2289/12462459/09ee391c-bf84-11e5-85f5-59a80095e883.png">

via https://www.casseroleclub.com via @sike13

**Comment by sike13** [comment]
Maybe I'm off-base, but I think of mission and values like this — a company's mission is external-facing and describes what we're doing, why it matters, and why the way we're doing it matters. A company's values is also external-facing, but essentially it gives people outside of Josephine HQ a chance to know a bit more about how we treat each other and conduct ourselves internally.

I think our current values are too similar to our mission statement and don't focus on us enough. As a company, we've weathered many storms and I think the honesty, openess, and dedication we've shown to one another are indicative of our values. Other people should be able to get a sense of that from our value statements. 

Perhaps an example could articulate this better:

> **Invest in people not output.** At Josephine, we care about the whole person blah blah blah. We think about the whole person not just the number of things they've crossed off their to-do list at the end of the day blah blah blah

^A pretty half-baked attempt at a new value but I guess what I want to articulate is we should have a value/set of values that speak to our experiences working together thus far. In my case, our team invested in me when I started here and because of that, I was still employed at Josephine even when attitude/visible negativity had a negative impact on my output/the team's output. In another environment, with another team, at another job I probably wouldn't have a job. Does that make sense?

**Comment by chawang90** [comment]
@sike13 re: Mission vs values, agree on them being too similar. That's why I think we drop 'serve the many serve the small' (it's covered in our mission), and potentially merge or axe 'measure feelings, not things' or 'details are everything'. 

Mission = **what** we're doing and **why** it matters
Values = **how** we treat each other and our community

I like what you're getting at with the invest in people not output - I think "be more human' needs to be better articulated, and should get across the message you're going for.

**Comment by chawang90** [comment]
Here's my rough draft of improved values:

Be More Human - **empathy**
Give Boldly, Give First - **trust**
Teach 'em How to Fish - **empowerment**

**Comment by chawang90** [comment]
To me:
1. Be More Human (**empathy**) is really about pushing our empathetic capacity. Caring about people even when it's hard or when society says we don't need to. I think this is at the core of what makes us better than other teams out there. 
2. Give Boldly, Give First (**trust**) - This is about trusting in people. Trust and faith seem to be intangible things you just commit to, but the act of trusting or having faith can be tangibly transformative.
3. Teach 'em How to Fish (**empowerment**)  - this is about empowerment. education improves but it also creates agency and pride. This hints at scale - the compounding impact of a network of empowered people is orders of magnitude larger than of a single group of individuals, a product, or a service.

**Comment by egustafson5** [comment]
I really love the "Values with Teeth" post. So true. My thoughts:

**Cultivate self-reliance** — what about "Do more than employ: empower"...or something. Don't love the phrasing, but the idea is there. We talk about that with our cooks and within our team; we don't see cooks as employees — they're customers who we're empowering to be their own employers. This also ties in nicely to our labor mission (but is it too similar?). We try to empower one another to be successful at work, too. 

I like keeping **Be More Human** w/ the explanation being that we invest in people over things.

I like the idea of **Details are everything** and think we do use that to make decisions pretty often. Just needs to be punchier; need to complete the thought of _why_ we think details matter. **Details define experiences**? 

**Give boldly, give first** is a keeper.

Agree @chawang90 that **serve the many, serve the small** could be cut from here & rolled in w/ labor. Although I do use that mantra when dealing with cook onboarding (when cooks are difficult, not tech savy, etc.), and we're trying to decide if someone is "worth it". This encourages me to not just look for people who are already crushing it (people like Renee).

**Measure feelings, not things** — first of all, not true. we do measure things, and those things matter (ahem, sales). but to me this is more about holistic / systemic thinking. so maybe it's something like **see the whole picture** (or something phrased better) or maybe it's about also measuring/valuing/taking into account the _intangibles_

**Comment by joyjding** [comment]
Really great feedback, Sika, and Emily. And thanks, Charley, for putting this together and pointing us toward B's post about Values with Teeth. I love Clef's articulation of their values, and kind of want to snag some of them! (Be better tomorrow than today comes to mind.)

Values
**Cultivate self-reliance**. I like the sentiment behind Teach em how to fish and I think the general idea is sound, but I feel like this has been said so many times in various contexts that it doesn't have the bite that it needs to be a compact value. I like the way it's placed now, in the text below the value. How about cultivate agency? Cultivate capability? Cultivate strength?  Someone get this woman a thesaurus.

**Details are everything**. This one is the one that always feels the _we're a startup_ language to me. What if we made it a subheader under something like: Measure pride, not credit. This one speaks to me, and is one I've repeated to myself.

**Be more human.** I really like this one. What it means to be "human" is a little vague,  though, and part of me wants to get vulnerability/authenticity/honesty in there. Like: we believe that it's possible to be a business and a family, to have honest, transparent communications with the people we interact with. 

**Serve the many, the small.** Agree about this being more about our labor mission.

**Give boldly, give first.** For me, the core of this value is more trust than altruism. I'd like the trust aspect to be articulated more. I really like Clef's version:  _We succeed together when we trust each other._

**Measure feelings, not things.** This is the value that I've always felt the weirdest about. Because...I don't know how to measure feelings. And I don't know what that means. And as Emily mentioned, we do measure things. I think it's a value that's less about measurement and more about building relationships. Something like: Build meaningful community. 

Another thing I'm thinking about that I don't know how to articulate: something about willingness to teach, and willingness to learn from anyone. In a lot of ways I prefer this to teach'em how to fish, because it assumes we're the authority (the teacher), but our community teaches us a lot too. When I first met Charley and Tal, what impressed me the most was the time they spent testing out the Josephine concept - learning, and figuring things out, and prototyping. What about something like: when we learn together, we grow together? Cheese city happening here.

**Comment by chawang90** [comment]
How do people feel about the revised 3 values? The ones on the site are already obsolete given our mission addition.

**Comment by terrybetts24** [comment]
I like the three revised values. You already captured what I was going to add as feedback.

**Comment by chawang90** [comment]
[New values for review](https://github.com/josephine/handbook/blob/master/Josephine%20Values.md)

**Comment by sike13** [comment]
@chawang90 — really well done. I especially loved how you framed **Give Boldly, Give First:** "our world’s systemic inequality means that people need different amounts of support to achieve the same outcomes."

Just one edit from this (under **Teach 'em How to Fish)**:

> Josephine’s impact on it’s community can only be sustainable and scalable

To this:

> Josephine’s impact on its community can only be sustainable and scalable

**Comment by joyjding** [comment]
When I read the first set of values (before applying for Josephine), they
really resonated with me. These resonate with me even more and are even
shorter! - great work.

A thought. I can't quite figure out how to phrase this, but the second
sentence in Teach'em how to fish more about helping a person to improve as
opposed to us improving people's livelihoods.

ie: The opportunity for pride and creative agency is crucial for helping
people to improve their own livelihoods.

**Comment by chawang90** [comment]
How about: 
- Pride and creative agency is a crucial part of improving peoples' livelihoods.  
- An individual's pride and creative agency are the most effective levers for improving their own livelihoods.

**Comment by chawang90** [comment]
We believe that the most meaningful improvements in a person's livelihood are inspired by their own pride, creative agency, and accountability.

**Comment by chawang90** [comment]
Comment when you've read or given a thumbs up so we can get this copy onto the website asap.

**Comment by egustafson5** [comment]
Minor copy edits:
At Josephine, our Values are used for navigation. Our Mission describes our desired destination, and our Values are the compass by which we stay on track. Our Values serve as mantras. They're written exactly the way they are said and used by our team to make decisions on a daily basis.

**Comment by talsafran** [comment]
I'm Tal Safran and I (finally) approve this message.

Charley, if this is good to go then close this issue, and also move the following issue into "This Week" and remove the "Blocked" tag :)

https://github.com/josephine/www/pull/620
